Webapps/config/routes.rb
Rails.application.routes.draw do

  resources :competitors
  resources :matches
  resources :competitions
  get 'pages/home'

  resources :channels do
    resources :updates
  end
  
  resources :sports 
  resources :users
  root 'pages#home'

  resources :chats do
    resources :messages
  end
  resources :groups do
    get "addnew"
    get "removeself"
  end
  
  resources :matches do
    member do
      patch 'goal'
      patch 'game_over'
    end
  end

  get    'index'   => 'users#index',  :as => :index
  get    'signup'  => 'users#new',    :as => :signup
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  get    'newasd'  => 'users#findex'
  

end

Webapps/app/models/match.rb
class Match < ActiveRecord::Base
    
  belongs_to :competition
  belongs_to :competitor1, class_name: "Competitor"
  belongs_to :competitor2, class_name: "Competitor"
  belongs_to :winner, class_name: "Competitor"
  belongs_to :winner_match, class_name: "Match"
  belongs_to :channel
  
  def start_time
    self.date.to_s.split(' ')[1]
  end
  
  def formatted_date
    date = self.date.to_s.split('-')
    "#{date[2].split(' ')[0]}-#{date[1]}-#{date[0]}" 
  end
  
end

Webapps/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy, :goal, :game_over]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @competition = @match.competition
    update_channel_name(@match)
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # PATCH /matches/1/goal
  def goal
    scorer = params.require(:match).permit(:scorer)[:scorer]
    competitor_scored scorer
    redirect_to @match
  end
  
  def game_over
    @match.match_finished = true
    @match.save
    update_tournament
    redirect_to @match
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)
    respond_to do |format|
      if @match.save
        format.html { redirect_to $redirect, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    @com1_old_score = @match.competitor1_score
    @com2_old_score = @match.competitor2_score
    respond_to do |format|
      if @match.update(match_params)
        update_tournament
        puts "Updating"
        update_channel_name(@match)
        update_channel_name(@match.winner_match) unless @match.winner_match.nil?
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:competition_id, :channel_id, :winner, :competitor1_score, :competitor2_score, :winner_match_pos, :match_finished)
    end
    
    def update_tournament
      if @match.match_finished
        set_winner_competitor
        broadcast_match_result(@match.channel)
        broadcast_match_result(@match.competition.channel)
        check_tournament_winner
      else
        broadcast_match_update
      end
    end
    
    def broadcast_match_result(channel)
      if @match.competitor1_score == @match.competitor2_score
        channel.updates.create(body: "#{@match.competitor1.name} vs #{@match.competitor2.name} has ended in a draw, #{@match.competitor1_score} - #{@match.competitor2_score}", user_id: channel.user_id)
      elsif winner_of_match == @match.competitor1
        channel.updates.create(body: "#{@match.competitor1.name} has won #{@match.competitor1_score} - #{@match.competitor2_score} against #{@match.competitor2.name}", user_id: channel.user_id)
      else
        channel.updates.create(body: "#{@match.competitor2.name} has won #{@match.competitor2_score} - #{@match.competitor1_score} against #{@match.competitor1.name}", user_id: channel.user_id)
      end
    end
    
    def broadcast_match_update
        if @com1_old_score != @match.competitor1_score
          @match.channel.updates.create(body: "#{@match.competitor1.name} has scored a goal against #{@match.competitor2.name}, #{@match.competitor1_score} - #{@match.competitor2_score}", user_id: @match.channel.user_id)
        elsif @com2_old_score != @match.competitor2_score
          @match.channel.updates.create(body: "#{@match.competitor2.name} has scored a goal against #{@match.competitor1.name}, #{@match.competitor2_score} - #{@match.competitor1_score}", user_id: @match.channel.user_id)
        else
          @match.channel.updates.create(body: "Nothing happened", user_id: @match.channel.user_id)
        end
    end
    
    def winner_of_match
      if @match.competitor1_score > @match.competitor2_score
        @match.competitor1
      else
        @match.competitor2
      end
    end
    
    def loser_of_match
      if @match.competitor1_score > @match.competitor2_score
        @match.competitor2
      else
        @match.competitor1
      end
    end
    
    def update_channel_name(match)
      if match.channel.nil?
        match.create_channel(user_id: current_user.id, name: "v")
        match.save
      end
      if match.channel.name == "v"
        if !match.competitor1.nil? and !match.competitor2.nil?
          match.channel.name = "#{match.competitor1.name} v #{match.competitor2.name}"
          match.channel.save
        end
      end
    end
    
    def set_winner_competitor
      if @match.winner_match
        winner = winner_of_match
        @match.winner = winner
        if @match.winner_match_pos == 1
          @match.winner_match.competitor1 = winner
        elsif @match.winner_match_pos == 2
          @match.winner_match.competitor2 = winner
        end
        @match.winner_match.save
      end
    end
    
    def competitor_scored(c)
      if c.to_i == 1
        @match.competitor1_score = @match.competitor1_score + 1
        @match.channel.updates.create(body: "#{@match.competitor1.name} has scored a goal against #{@match.competitor2.name}, #{@match.competitor1_score} - #{@match.competitor2_score}", user_id: @match.channel.user_id)
      else
        @match.competitor2_score = @match.competitor2_score + 1
        @match.channel.updates.create(body: "#{@match.competitor2.name} has scored a goal against #{@match.competitor1.name}, #{@match.competitor2_score} - #{@match.competitor1_score}", user_id: @match.channel.user_id)
      end
      @match.save
    end
    
    def check_tournament_winner
      if @match.round ==  Math.log2(@match.competition.competitors.length).to_i + 1 && @match.match_finished
        winner = winner_of_match
        @match.competition.winner = winner
        @match.competition.channel.updates.create(body: "#{winner.name} has won the tournament", user_id: 0)
        @match.competition.save
      end
    end
    
end

Webapps/app/helpers/matches_helper.rb
module MatchesHelper
    
  def user_has_competed_in?(match)
    competitor1 = match.competitor1
    competitor2 = match.competitor2
    if competitor1.nil? && competitor2.nil?
      false
    elsif competitor1.nil?
      user_is_competitor?(competitor2) 
    elsif competitor2.nil?
      user_is_competitor?(competitor1)
    else
      user_is_competitor?(competitor1) || user_is_competitor?(competitor2) 
    end
  end
  
  def user_is_competitor?(competitor)
    user = current_user
    user == competitor.user
  end
  
  def round_name(round_number, competition)
    rounds = Math.log2(competition.competitors.length).ceil
    if rounds == 1
      "Final"  
    elsif rounds == 2
      if round_number == 1
        "Semi-Final"
      else
        "Final"
      end
    elsif rounds == 3
      if round_number == 1
        "Quarter-Final"  
      elsif round_number == 2
        "Semi-Final"
      else
        "Final"
      end
    else
      if rounds == round_number
        "Final"
      elsif rounds - 1 == round_number
        "Semi-Final"
      elsif rounds - 2 == round_number
        "Quarter-Final"
      else
        "Round #{round_number}"
      end
    end
  end
  
end

Webapps/app/views/matches/_form.html.erb
<div class="col-md-2">
<%= form_for @match, :url => url_for(goal_match_path), :remote => true do |f| %>
  <%= f.hidden_field :scorer, :value => 1 %>
  <%= f.submit "#{@match.competitor1.name} scored", :class => "btn btn-primary" %>
<% end %>
</div>

<div class="col-md-2">
<%= form_for @match, :url => url_for(game_over_match_path), :remote => true do |f| %>
  <%= f.submit "Game Over", :class => "btn btn-primary" %>
<% end %>
</div>

<div class="col-md-2">
<%= form_for @match, :url => url_for(goal_match_path), :remote => true do |f| %>
  <%= f.hidden_field :scorer, :value => 2 %>
  <%= f.submit "#{@match.competitor2.name} scored", :class => "btn btn-primary" %>
<% end %>
</div>

Webapps/app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

Webapps/app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Match History</h1>

<% create_tournament %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Match</th>
      <th>P1 Name</th>
      <th>P1 Score</th>
      <th>P2 Score</th>
      <th>P2 Name</th>
      <th>Competition</th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <% if user_has_competed_in?(match) && match.competitor1 && match.competitor2 %>
        <tr>
          <td><%= link_to "#{match.competitor1.name} v #{match.competitor2.name}", match%></td>
          <td><%= link_to match.competitor1.name, match.competitor1 %></td>
          <td><%= match.competitor1_score %></td>
          <td><%= match.competitor2_score %></td>
          <td><%= link_to match.competitor2.name, match.competitor2 %></td>
          <td><%= link_to match.competition.name, match.competition %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

Webapps/app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

Webapps/app/views/matches/show.html.erb
<div class="container">
<div class="col-md-8">
<p id="notice"><%= notice %></p>
<h2><%= @match.competition.name %> <%= @competition.season_as_string %></h2>
<div class="col-lg-8">
  <table class="table" id="match-table">
    <tbody>
      <tr>
        <td>
          <span class="match-competitor">
            <% if @match.competitor1.user %>
              <%= link_to @match.competitor1.name, @match.competitor1.user %>
            <% else %>
              <%= @match.competitor1.name %>
            <% end %>
          </span>
        </td>
        <td style="text-align: bottom;"><span style="font-size: 120%">vs</span></td>
        <td>
          <span class="match-competitor">
            <% if @match.competitor2.user %>
              <%= link_to @match.competitor2.name, @match.competitor2.user %>
            <% else %>
              <%= @match.competitor2.name %>
            <% end %>
          </span>
        </td>
      </tr>
      <tr>
        <td>
          <span class="match-score">
            <%= @match.competitor1_score %>
          </span>
        </td>
        <td>
        </td>
        <td>
          <span class="match-score">
            <%= @match.competitor2_score %>
          </span>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<div class="col-lg-8">
  <table class="table">
    <tbody>
      <tr>
        <td></td>
        <td>Date: <%= @match.formatted_date %></td>
        <td>Time: <%= @match.start_time %></td>
      </tr>
      <tr>
        <td><b>Details</b></td>
        <td>Match Time:</td>
        <td><%= @match.time %></td>
      </tr>
      <tr>
        <td>Formation</td>
        <td><%= @match.home_formation %></td>
        <td><%= @match.away_formation %></td>
      </tr>
      <tr>
        <td>Defense</td>
        <td><%= @match.home_defense %></td>
        <td><%= @match.away_defense %></td>
      </tr>
      <tr>
        <td>Midfield</td>
        <td><%= @match.home_midfield %></td>
        <td><%= @match.away_midfield %></td>
      </tr>
      <tr>
        <td>Forwards</td>
        <td><%= @match.home_forward %></td>
        <td><%= @match.away_forward %></td>
      </tr>
      <tr>
        <td>Substitutes</td>
        <td><%= @match.home_subs %></td>
        <td><%= @match.away_subs %></td>
      </tr>
      <tr>
        <td>Yellow Cards</td>
        <td><%= @match.home_yellows %></td>
        <td><%= @match.away_yellows %></td>
      </tr>
      
    </tbody>
  </table>
</div>
</div>



<div class ="col-md-4">
  <% $redirect = @match %>
  <% @channel = @match.channel %>
  <%= render @channel unless @channel.nil? %>
</div>
</div>

<%= render 'form' %>