Webapps/config/routes.rb
Rails.application.routes.draw do

  resources :competitors
  resources :matches
  resources :competitions
  get 'pages/home'

  resources :channels do
    resources :updates
  end
  
  resources :sports 
  resources :users
  root 'pages#home'

  resources :chats do
    resources :messages
  end
  resources :groups do
    get "addnew"
    get "removeself"
  end
  
  resources :matches do
    member do
      patch 'goal'
      patch 'game_over'
    end
  end

  get    'index'   => 'users#index',  :as => :index
  get    'signup'  => 'users#new',    :as => :signup
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  get    'newasd'  => 'users#findex'
  

end

Webapps/app/models/channel.rb
class Channel < ActiveRecord::Base
    validates :user_id, presence: true
    validates :name, presence: true, length: { within: 1..40 }
    
    has_many :updates, dependent: :destroy
    has_many :chats, :class_name => "Chat", :foreign_key => "context", dependent: :destroy
    accepts_nested_attributes_for :updates
end

Webapps/app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]
  before_filter :user_is_signed_in

  # GET /channels
  # GET /channels.json
  def index
    redirect_to root_url
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:user_id, :name, update_attributes: [:body, :user_id])
    end
end

Webapps/app/helpers/channels_helper.rb
module ChannelsHelper
end

Webapps/app/views/channels/_channel.html.erb
<script src="//js.pusher.com/2.2/pusher.min.js"></script>
<script>
// If your Heroku application is within the EU region,
// uncomment the followling lines
// Pusher.host = 'ws-eu.pusher.com';
// Pusher.sockjs_host = 'sockjs-eu.pusher.com';

var pusher = new Pusher('<%= Pusher.key %>'); // uses your APP KEY
var channel = pusher.subscribe("channel<%= channel.id %>");
channel.bind('update', function(data) {
  //alert(data.body);
  html = [];
  var div = $( "#home" )
  var ul = div.find('#cbox')//document.getElementById("chatbox");
  

  div.find("#chatjx")[0].reset();
  html.push('<li class="left clearfix"><span class="chat-img pull-left">');
  <% if @competition.image? %>
    html.push('    <%= image_tag @competition.image_url(:thumb), class: "img-circle", size: "50" %>');
  <% else %>
    html.push('    <%= image_tag url_for("sports/#{@competition.sport.name}.png"), class: "img-circle", size: "50" %>');
  <% end %>
  html.push('</span>');
  html.push('  <div class="chat-body clearfix">');
  html.push('      <div class="header">');
  html.push('          <strong class="primary-font">');
    html.push(data.user);
    html.push('</strong><small class="pull-right text-muted">');
  html.push('             <span class="glyphicon glyphicon-time"></span> just now');
    html.push('       </small>');
  html.push('      </div>');
  html.push('      <p>');
    html.push(data.body);
  html.push('      </p>');
  html.push('  </div>');
  html.push('</li>');
  
  
  ul.append(html.join(' '));

  var d = div.find('#cpanel');
  //d.scrollTop(d.prop("scrollHeight"));
  
  d.animate({ scrollTop: d[0].scrollHeight}, 1000);

  //alert(html.join(' '));
  
});
</script>



  <div role="tabpanel">
  
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Cast</a></li>
      <li role="presentation"><a href="#newchat" aria-controls="newchat" role="tab" data-toggle="tab">New</a></li>

    <% channel.chats.each do |chat| %>
      <% if chat.group.users.include? current_user %>
      <li role="presentation"><a href="#chat<%= chat.id %>" aria-controls="<%= chat.id %>" role="tab" data-toggle="tab"><%= chat.name %></a></li>
      <% end %>
    <% end %>
    </ul>
  
    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="home">
        
        <div class="panel panel-primary">
          <div class="panel-heading">
              <%= channel.name %>
          </div>
          <div class="panel-body">
              <ul id="chatbox" class="chat">
                <div id="cbox">
                  <% channel.updates.each do |message| %>
                      <li class="left clearfix"><span class="chat-img pull-left">
                        <% if @competition.image? %>
                          <%= image_tag @competition.image_url(:thumb), class: "img-circle", size: "50" %>
                        <% else %>
                          <%= image_tag url_for("sports/#{@competition.sport.name}.png"), class: "img-circle", size: "50" %>
                        <% end %>
                      </span>
                          <div class="chat-body clearfix">
                              <div class="header">
                                  <strong class="primary-font">Broadcaster</strong> <small class="pull-right text-muted">
                                      <span class="glyphicon glyphicon-time"></span><%=  message.created_at %></small>
                              </div>
                              <p>
                                  <%= message.body %>
                              </p>
                          </div>
                      </li>
                  <% end %>
                </div>
              </ul>
          </div>
          <div class="panel-footer">
            <% if current_user.id == channel.user_id %>
              <%= simple_form_for [channel, channel.updates.build], remote:true, html: { :id => "chatjx" }  do |f| %>
                  <%= f.hidden_field :user_id, :value => current_user.id %>
                  <%= f.input :body, :label => false, wrapper_html: {class: "form-inline"} do %>
                    <%= f.input :body, :label => false, :as => :string, :input_html => { size: 30, placeholder: "Type...", class: "form-control input-sm"}%>
                    <%= f.button :submit, "Send", :class => "btn btn-warning btn-sm" %>
                  <% end %>
                </p>
              <% end %>
            <% end %>
          
          </div>
      </div>
        
      </div>
      
    <% channel.chats.each do |chat| %>
      <% if chat.group.users.include? current_user %>
      <div role="tabpanel" class="tab-pane" id="chat<%= chat.id %>"> <%= render chat%></div>
      <% end %>
    <% end %>
    
      <div role="tabpanel" class="tab-pane" id="newchat"><% @chat = Chat.new %><%= render :partial => 'chats/form' %></div>
    </div>
  
  </div>

Webapps/app/views/channels/_form.html.erb
<%= simple_form_for(@channel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Webapps/app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

Webapps/app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Channels</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.user_id %></td>
        <td><%= channel.name %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>

Webapps/app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

Webapps/app/views/channels/show.html.erb
<% @redirect = @channel %>
<%= render @channel %>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>