Webapps/config/routes.rb
Rails.application.routes.draw do

  resources :competitors
  resources :matches
  resources :competitions
  get 'pages/home'

  resources :channels do
    resources :updates
  end
  
  resources :sports 
  resources :users
  root 'pages#home'

  resources :chats do
    resources :messages
  end
  resources :groups do
    get "addnew"
    get "removeself"
  end
  
  resources :matches do
    member do
      patch 'goal'
      patch 'game_over'
    end
  end

  get    'index'   => 'users#index',  :as => :index
  get    'signup'  => 'users#new',    :as => :signup
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  get    'newasd'  => 'users#findex'
  

end

Webapps/app/models/competitor.rb
class Competitor < ActiveRecord::Base
    
    belongs_to :competition
    belongs_to :user

end

Webapps/app/controllers/competitors_controller.rb
class CompetitorsController < ApplicationController
  before_action :set_competitor, only: [:show, :edit, :update, :destroy]

  # GET /competitors
  # GET /competitors.json
  def index
    @competitors = Competitor.all
  end

  # GET /competitors/1
  # GET /competitors/1.json
  def show
  end

  # GET /competitors/new
  def new
    @competitor = Competitor.new
  end

  # GET /competitors/1/edit
  def edit
  end

  # POST /competitors
  # POST /competitors.json
  def create
    @competitor = Competitor.new(competitor_params)
    respond_to do |format|
      if @competitor.save
        format.html { redirect_to @competitor, notice: 'Competitor was successfully created.' }
        format.json { render :show, status: :created, location: @competitor }
      else
        format.html { render :new }
        format.json { render json: @competitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitors/1
  # PATCH/PUT /competitors/1.json
  def update
    respond_to do |format|
      if @competitor.update(competitor_params)
        format.html { redirect_to @competitor, notice: 'Competitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @competitor }
      else
        format.html { render :edit }
        format.json { render json: @competitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitors/1
  # DELETE /competitors/1.json
  def destroy
    @competitor.destroy
    respond_to do |format|
      format.html { redirect_to competitors_url, notice: 'Competitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competitor
      @competitor = Competitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competitor_params
      params.require(:competitor).permit(:name, :user)
    end
end

Webapps/app/helpers/competitors_helper.rb
module CompetitorsHelper
end

Webapps/app/views/competitors/_form.html.erb
<%= simple_form_for(@competitor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Webapps/app/views/competitors/edit.html.erb
<h1>Editing Competitor</h1>

<%= render 'form' %>

<%= link_to 'Show', @competitor %> |
<%= link_to 'Back', competitors_path %>

Webapps/app/views/competitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Competitors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @competitors.each do |competitor| %>
      <tr>
        <td><%= competitor.name %></td>
        <td><%= link_to 'Show', competitor %></td>
        <td><%= link_to 'Edit', edit_competitor_path(competitor) %></td>
        <td><%= link_to 'Destroy', competitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competitor', new_competitor_path %>

Webapps/app/views/competitors/new.html.erb
<h1>New Competitor</h1>

<%= render 'form' %>

<%= link_to 'Back', competitors_path %>

Webapps/app/views/competitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @competitor.name %>
</p>

<%= link_to 'Edit', edit_competitor_path(@competitor) %> |
<%= link_to 'Back', competitors_path %>