Webapps/config/routes.rb
Rails.application.routes.draw do

  resources :competitors
  resources :matches
  resources :competitions
  get 'pages/home'

  resources :channels do
    resources :updates
  end
  
  resources :sports 
  resources :users
  root 'pages#home'

  resources :chats do
    resources :messages
  end
  resources :groups do
    get "addnew"
    get "removeself"
  end
  
  resources :matches do
    member do
      patch 'goal'
      patch 'game_over'
    end
  end

  get    'index'   => 'users#index',  :as => :index
  get    'signup'  => 'users#new',    :as => :signup
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  get    'newasd'  => 'users#findex'
  

end

Webapps/app/models/competition.rb
class Competition < ActiveRecord::Base
  
  has_many :matches
  belongs_to :user
  belongs_to :channel
  has_many :competitors
  belongs_to :sport
  belongs_to :group
  belongs_to :winner, class_name: "Competitor"
  mount_uploader :image, ImageUploader, :mount_on => :image 
  
  accepts_nested_attributes_for :competitors
  
  def season_as_string
    if self.curr_season
      "20#{self.curr_season[0..1]}-20#{self.curr_season[2..3]}"
    end
  end
    
end

Webapps/app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  helper CompetitionsHelper
  before_action :set_competition, only: [:show, :edit, :update, :destroy]
  after_action :update_competitor_names, only: [:create]

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    @rounds = set_rounds
    @matches = @competition.matches.select { |match| match.season == @competition.curr_season }
    @matches = @matches.sort_by{ |m| m.round }
  end

  # GET /competitions/new
  def new
    @sport = Sport.find(params[:sport_id])
    @competition = Competition.new
    @groups = Group.all.select { |group| includes_curr_user?(group) }
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)
    add_group_users_to_competition # if exists
    create_channel
    respond_to do |format|
      if @competition.save
        generate_fixtures
        format.html { redirect_to @competition, notice: "Competition #{@competition.competition_type} was successfully created." }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:name, :sport_id, :user_id, :competition_type, :image, :group_id, :curr_season, competitors_attributes: [:id, :name, :_destroy, :user_id, :user])
    end
    
    def create_channel
      ch = Channel.create(:name => @competition.name, :user_id => @competition.user_id)
      @competition.channel_id = ch.id
    end
   
    def generate_fixtures
      update_competitor_names
      case @competition.competition_type
        when 1 # Single Round Robin
          generate_single_rr
        when 2 # Double Round Robin
          generate_double_rr
        when 3 # Tournament
          generate_tournament
      end
    end
    
  def generate_single_rr
    @fixtures = @competition.competitors.to_a.combination(2).to_a
    @fixtures.each do |fixture|
      match = @competition.matches.build()
      match.competitor1 = fixture[0]
      match.competitor2 = fixture[1]
      match.create_channel(user_id: current_user.id, name: "#{match.competitor1.name} vs #{match.competitor2.name}")
      match.save
    end
  end
  
  def generate_double_rr
    2.times { generate_single_rr }
  end
  
  def generate_tournament
    num_competitors = @competition.competitors.length
    @curr_round = Array.new(Math.log2(num_competitors)+1)
    @fixtures = @competition.competitors.to_a
    next_round = build_first_two_rounds
    if num_competitors > 3
      build_playoffs next_round
    end
  end
  
  def build_first_two_rounds
    num_competitors = @competition.competitors.length
    if Math.log2(num_competitors) % 1 == 0 # if regular bracket size (base 2)
      i = 0
      while i < num_competitors/2 do
        match = @competition.matches.build()
        match.competitor1 = @fixtures[(2*i)]
        match.competitor2 = @fixtures[(2*i)+1]
        match.round = 1
        match.create_channel(user_id: current_user.id, name: "#{match.competitor1.name} vs #{match.competitor2.name}")
        match.save
        @curr_round[i] = match
        i = i + 1
      end 
      return 2
    else # irregular bracket size
      i = 0
      rounds = Math.log2(num_competitors).to_i
      num_first_round = num_competitors - 2**(rounds - 1)
      # creating second round of matches
      puts rounds
      while i < 2**(rounds-1) do
        match = @competition.matches.build()
        match.competitor1 = @fixtures[(2*i)]
        match.competitor2 = @fixtures[(2*i)+1]
        match.round = 2
        match.create_channel(user_id: current_user.id, name: "#{match.competitor1.name} vs #{match.competitor2.name}")
        match.save
        puts match.channel.name
        @curr_round[i] = match
        i = i + 1
      end 
      i = i*2
      m = 0
      # storing extra competitors
      @spares = Array.new(num_first_round)
      while i < num_competitors do
        @spares[m] = @fixtures[i]
        puts "#{i}:#{@fixtures[i].name}"
        i = i + 1
        m = m + 1
      end
      i = 0
      # populate first round with extra competitors
      while i < m do
        match = @competition.matches.build()
        match.create_channel(user_id: current_user.id, name: match)
        if i % 2 == 0
          comp = @curr_round[i/2].competitor1
          @curr_round[i/2].competitor1 = nil
          match.competitor1 = comp
          match.competitor2 = @spares[i]
          match.winner_match_pos = 1
        else
          comp = @curr_round[i/2].competitor2
          @curr_round[i/2].competitor2 = nil
          match.competitor2 = comp
          match.competitor1 = @spares[i]
          match.winner_match_pos = 2
        end
          match.channel.name = "#{match.competitor1.name} vs #{match.competitor2.name}"
          match.channel.save
          match.winner_match = @curr_round[i/2]
          match.winner_match.save
          match.round = 1
          match.save
          i = i + 1
      end
      3
    end
  end

  def build_playoffs(round)
    while @curr_round.length > 1
      num_matches = @curr_round.length/2
      @next_round = Array.new(num_matches)
      i = 0
      num_matches.times {
        puts "looping in playoffs"
        match = @competition.matches.create()
        match.round = round
        match.create_channel(user_id: current_user.id, name: "v")
        @next_round[i] = match
        set_next_match(@curr_round[(2*i)],match,i,1)
        set_next_match(@curr_round[(2*i)+1],match,i,2)
        i += 1
      }
      @curr_round.each do |m|
        m.save unless m.nil?
      end
      @curr_round = @next_round
      round += 1
    end
    @curr_round[0].round = round - 1
    @curr_round[0].save
  end
  
  def set_next_match(comp, match, i, pos)
    puts "settingnextmatch"
    if comp.is_a? Competitor
      puts comp.name
      if pos == 1
        match.competitor1 = comp
      else
        match.competitor2 = comp
      end
    elsif comp.is_a? Match
      @curr_round[(2*i)+(pos-1)].winner_match = match
      @curr_round[(2*i)+(pos-1)].winner_match_pos = pos
    end
  end

  def set_rounds
    num_rounds = Math.log2(@competition.competitors.length) + 1
    rounds = Array.new(num_rounds)
    final = @competition.matches.where(round: num_rounds).to_a
    rounds.unshift(final)
    bracket = @competition.matches.where(round: num_rounds-1).to_a
    i=0
    (rounds.length - 1).times do 
      rounds.unshift(bracket)
      bracket = @competition.matches.where(round: (num_rounds-2-i)).to_a
      i+=1
    end
    rounds = rounds.reject {|r| r == [] || r.nil?}
    return rounds
  end
  
  def set_rounds1
    rounds = Array.new(Math.log2(@competition.competitors.length) + 1)
    final = @competition.matches.where(winner_match: nil).to_a
    rounds.unshift(final)
    bracket = @competition.matches.where(winner_match: final).to_a
    (rounds.length - 1).times do 
      rounds.unshift(bracket)
      bracket = @competition.matches.where(winner_match: bracket).to_a
    end
    rounds = rounds.reject {|r| r == [] || r.nil?}
    puts "##### #{rounds} #####"
    puts "##### #{@competition.matches.where(winner_match: !nil).to_a} ########"
    return rounds
  end
    
  def update_competitor_names
    @competition.competitors.each do |competitor|
      if competitor.name == ""
        competitor.name = competitor.user.username
        competitor.save
      end
    end
  end
  
  def add_group_users_to_competition
    if !@competition.group.nil?
      @competition.group.users.each do |g|
        if !g.nil?
          c = Competitor.create(user: g, name: g.username, competition_id: @competition.id)
          @competition.competitors << c
          c.save
        end
      end
      @competition.save
    end
  end
    
end

Webapps/app/helpers/competitions_helper.rb
module CompetitionsHelper
  def render_score(m, id)
    if id == 1
      if m.competitor1_score > m.competitor2_score
        render html: "<div class='match_winner'>#{m.competitor1_score}</div>".html_safe
      else
        render html: "<div>#{m.competitor1_score}</div>".html_safe
      end
    else
      if m.competitor2_score > m.competitor1_score
        render html: "<div class='match_winner'>#{m.competitor2_score}</div>".html_safe
      else
        render html: "<div>#{m.competitor2_score}</div>".html_safe
      end
    end
  end
  
  def count_wins(c)
    count = 0
    matches = @matches.select{|match| match.competitor1 == c or match.competitor2 == c}
    matches.each do |match|
      if match.match_finished
        if match.competitor1_score > match.competitor2_score
          if match.competitor1 == c
            count += 1
          end
        elsif match.competitor2_score > match.competitor1_score
          if match.competitor2 == c
            count += 1
          end
        end
      end
    end
    count
  end  

  def count_loses(c)  
    count = 0
    matches = @matches.select{|match| match.competitor1 == c or match.competitor2 == c}
    matches.each do |match|
      if match.match_finished
        if match.competitor1_score < match.competitor2_score
          if match.competitor1 == c
            count += 1
          end
        elsif match.competitor2_score > match.competitor1_score
          if match.competitor2 == c
            count += 1
          end
        end
      end
    end
    count
  end
  
  def count_draws(c)
    count = 0
    matches = @matches.select{|match| match.competitor1 == c or match.competitor2 == c}
    matches.each do |match|
      if match.competitor1_score == match.competitor2_score && match.match_finished
        count = count + 1
      end
    end
    count
  end
  
  def get_table_details(c)
    returnHash = { :wins => 0, :loses => 0, :draws => 0, :points => 0, :for => 0, :against => 0, :season => 0 }
    matches = @matches.select{|match| match.competitor1 == c or match.competitor2 == c}
    matches.each do |match|
      returnHash[:season] = match[:season]
      if match.match_finished
        returnHash[:for] = returnHash[:for] + match.competitor1_score
        returnHash[:against] = returnHash[:against] + match.competitor2_score
        if match.competitor1_score == match.competitor2_score
          returnHash[:draws] = returnHash[:draws] + 1
          returnHash[:points] = returnHash[:points] + 1
        elsif match.competitor1_score > match.competitor2_score
          if match.competitor1 == c
            returnHash[:wins] = returnHash[:wins] + 1
            returnHash[:points] = returnHash[:points] + 3            
          else
            returnHash[:loses] = returnHash[:loses] + 1
          end
        else
          if match.competitor1 == c
            returnHash[:loses] = returnHash[:loses] + 1
          else 
            returnHash[:wins] = returnHash[:wins] + 1
            returnHash[:points] = returnHash[:points] + 3 
          end
        end
      end
    end
    returnHash
  end
  
end

Webapps/app/views/competitions/_competitor_fields.html.erb
<div class="form-group">
  <div class="fields row">
    <div class="col-lg-6">
        <div class="col-md-4"><div class="dropdown"><%= f.collection_select(:user_id, User.all, :id, :username, {:include_blank => "Select a User"}, { :class => "btn btn-primary dropdown-toggle" })  %></div></div>
        <div class="col-md-7"><%= f.text_field :name, class: "form-control", :placeholder => "or write a name here" %></div>
        <div class="col-md-1">
          <%  if not params[:action] == 'edit'  %>
            <span class="input-group-btn" tabindex=-1>
            <%=   link_to_remove_fields "remove", f %>
            </span>
          <%  end %>
        </div>
      </div>
    </div> 
  </div>

Webapps/app/views/competitions/_competitors.html.erb
 <h1></h1>
 <div class = "form group">
   <div class="fields row">
      <div class="col-lg-6">
         <div class="col-lg-4"></div><div class="col-lg-2"><%= f.select(:group_id, Group.order(:name).map {|x| [x.name_with_length, x.id] }, {:include_blank => "Select a Group"}, { :class => "btn btn-primary dropdown-toggle" })  %></div>
      </div>
   </div>
 </div>
 <h3>
 and/or add competitors seperately
</h3>
<h2></h2>
 <div id="competitor_fields">
  <%= f.fields_for :competitors do |builder| %>
      <%= render "competitor_fields", :f => builder %>
  <% end %>
 </div>
  
              
<div class="form-group">
<div class="fields row">
  <div class="form-group col-lg-6">
    <div style="float: left"><%= link_to_add_fields "Add Competitor", f, :competitors %></div>
  </div>
</div>
</div>
<div class="form-group">
<div class="fields row">
  <div class="form-group col-lg-6">
    <div style="float: right"><%= f.submit class: "btn btn-primary", id: "league_submit"%></div>
  </div>
</div>
</div> 

Webapps/app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="form-group col-lg-6">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control", :placeholder => "League name" %>
    </div>
  </div>
  <% if not params[:action] == 'edit' %>
  <%= f.hidden_field :sport_id, :value => @sport.id %>
  <% end %>
  <%= f.label "Competition Type:" %>
  <div class="field">  
   <%= f.radio_button :competition_type, "1" %>
   <%= label :competition_type, "Single Round Robin" %>
   </div>
  <div class="field">
   <%= f.radio_button :competition_type, "2" %>
   <%= label :competition_type, "Double Round Robin" %>
   </div>
  <div class="field">
   <%= f.radio_button :competition_type, "3" %>
   <%= label :competition_type, "Tournament" %>
  </div>
  <% if not params[:action] == 'edit' %>
    <%= label "label", :name, "Competitors" %>
    <%= render "competitors", :f => f %>
  <% end %>

<% end %>

Webapps/app/views/competitions/_image_upload.html.erb
<%= form_for @competition do |f| %>
<div class="control-group">
  <p>
    <%= f.file_field :image %>
  </p>
  <div class="controls">
  <p>
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </p>
  </div></div>
  <%= f.submit "Save Competition Picture", :class => 'btn btn-primary' %>
<% end %>

Webapps/app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form' %>

<h1>Upload Picture</h1>
<%= render 'image_upload'%>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

Webapps/app/views/competitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Competitions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.name %></td>
        <td><%= link_to 'Show', competition %></td>
        <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
        <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competition', new_competition_path %>

Webapps/app/views/competitions/new.html.erb
<h1>New <%= @sport.name %> Competition</h1>
<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

Webapps/app/views/competitions/show.html.erb
<%= stylesheet_link_tag    'tournament'  %>
<div class="container">
<div class="col-md-7">
  
<div>
  <div class="row">
    <p>
      <h2>
        <% if @competition.image.file.nil? %>
          <%= image_tag image_url("sports/#{@competition.sport.name}.png"), size: "36" %>
        <% else %>
          <%= image_tag @competition.image_url(:thumb) if @competition.image? %>
        <% end %>
        <%= @competition.name %> <%= @competition.season_as_string %>
        <small style="font-size: 32%; padding-left: 10px">
          <% if current_user.id == @competition.user_id %>
          <%= link_to 'Edit', edit_competition_path(@competition) %>
          <% end %>
          
        </small>
      </h2>
    </p>
  </div>
  
  <% if @competition.curr_season %>
    <div class="row">
    <%= form_for(@competition) do |f| %>
    <%= f.select :curr_season, 
    options_for_select([["2012-2013","1213"],["2013-2014","1314"],["2014-2015","1415"],["2015-2016","1516"]], 
    @competition.curr_season), :class => "btn btn-primary" %>
    <%= f.submit "Select Season" %>
    <% end %>
    </div>
  <% end %>
  <% if @competition.competition_type == 3 %>
  <div >
        <div class="row">
          <% i = 1 %>
          <h1></h1>
          <% @rounds.each do |r| %>
            <h3><%= round_name(i, @competition) %></h3>
            <% i = i + 1 %>
            <table class="table table-hover list-table">
              <tbody>
                <% r.each do |m| %>
                  <% if m.competitor1 and m.competitor2 %>
                    <tr onclick="location.href='<%= match_path(m) %>'"  style="cursor:pointer">
                      <td class="col-md-2"><%= m.competitor1.name %></td>
                      <td class="col-md-1"> vs </td>
                      <td class="col-md-2"><%= m.competitor2.name %></td>
                      <td class="col-md-1"><%= render_score m, 1 %></td>
                      <td class="col-md-1">-</td>
                      <td class="col-md-1"><%= render_score m, 2 %></td>
                    </tr> 
                  <% elsif m.competitor1 %>
                    <tr>
                      <td class="col-md-2"><%= m.competitor1.name %></td>
                      <td class="col-md-1"> vs </td>
                      <td class="col-md-2"> TBC </td>
                      <td class="col-md-1"><%= render_score m, 1 %></td>
                      <td class="col-md-1">-</td>
                      <td class="col-md-1"><%= render_score m, 2 %></td>
                    </tr> 
                  <% elsif m.competitor2 %>
                    <tr>
                      <td class="col-md-2"> TBC </td>
                      <td class="col-md-1"> vs </td>
                      <td class="col-md-2"><%= m.competitor2.name %></td>
                      <td class="col-md-1"><%= render_score m, 1 %></td>
                      <td class="col-md-1">-</td>
                      <td class="col-md-1"><%= render_score m, 2 %></td>
                    </tr> 
                  <% else %>
                    <tr>
                      <td class="col-md-2"></td>
                      <td class="col-md-1"> TBD </td>
                      <td class="col-md-2"></td>
                      <td class="col-md-1"></td>
                      <td class="col-md-1"></td>
                      <td class="col-md-1"></td>
                    </tr>   
                  <% end %>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>  
  <% elsif @competition.curr_season.nil? %>
    <div style="padding-top: 30px">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#ranking" aria-controls="ranking" role="tab" data-toggle="tab">Ranking</a></li>
      <li role="presentation"><a href="#fixtures" aria-controls="fixtures" role="tab" data-toggle="tab">Fixtures</a></li>
    </ul>
  
    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="ranking">
        <div class="row">
            <table class="table table-hover list-table">
              <thead>
                <th>#</th>
                <th>Name</th>
                <th>Wins</th>
                <th>Loses</th>
                <th>Draws</th>
              </thead>
              <tbody>
                <% i = 1 %>
                <% @competition.competitors.sort_by{|comp| -(count_wins comp)}.each do |c| %>
                  <tr>
                    <td><%= i %></td>
                    <td><%= c.name %></td>
                    <td><%= count_wins c %></td>
                    <td><%= count_loses c %></td>
                    <td><%= count_draws c %></td>
                  </tr>
                  <% i = i + 1 %>
                <% end %>
              </tbody>
            </table>  
        </div>
      </div>
        <div role="tabpanel" class="tab-pane fade" id="fixtures">
          <div class="row">
              <table class="table table-hover list-table" id="match_table" >
                <tbody>
                  <% @competition.matches.each do |m| %>
                    <% if m.competitor1 and m.competitor2 %>
                      <tr style="cursor:pointer">
                        <td class="col-md-2"><%= m.competitor1.name %></td>
                        <td class="col-md-1"> vs </td>
                        <td class="col-md-2"><%= m.competitor2.name %></td>
                        <td class="col-md-1"><%= render_score m, 1 %></td>
                        <td class="col-md-1">-</td>
                        <td class="col-md-1"><%= render_score m, 2 %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
          </div>
        </div>
    </div>
    </div>
  <% else %>
  <div style="padding-top: 30px">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#ranking" aria-controls="ranking" role="tab" data-toggle="tab">Ranking</a></li>
    <li role="presentation"><a href="#fixtures" aria-controls="fixtures" role="tab" data-toggle="tab">Fixtures</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="ranking">
      <div class="row">
          <table class="table table-hover list-table">
            <thead>
              <th>#</th>
              <th>Name</th>
              <th>Wins</th>
              <th>Loses</th>
              <th>Draws</th>
              <th>Points</th>
              <th>F</th>
              <th>A</th>
              <th>GD</th>
            </thead>
            <tbody>
              <% i = 1 %>
              <% @competition.competitors.sort_by{|comp| -(count_wins comp)}.each do |c| %>
              <% details = get_table_details c %>
                <% if details[:season] == @competition.curr_season %>
                <tr>
                  <td><%= i %></td>
                  <td><%= c.name %></td>
                  <td><%= details[:wins] %></td>
                  <td><%= details[:loses] %></td>
                  <td><%= details[:draws] %></td>
                  <td><%= details[:points] %></td>
                  <td><%= details[:for] %></td>
                  <td><%= details[:against] %></td>
                  <td><%= details[:for] - details[:against] %></td>
                </tr>
                <% end %>
                <% i = i + 1 %>
              <% end %>
            </tbody>
          </table>  
      </div>
    </div>
      <div role="tabpanel" class="tab-pane fade" id="fixtures">
        <div class="row">
          <% week = 0 %>
          <table><tbody>
            <h1></h1>
          <% @matches.each do |m| %>
            <% if m.competitor1 and m.competitor2 %>
              <% if week != m.round %>
              <%= "Week #{week}" unless week == 0 %>
                </tbody>
                </table>
                <table class="table table-hover list-table" id="match_table" >
                  <tbody>
              <% end %>
              <tr style="cursor:pointer">
                <%= hidden_field_tag 'match_id', m.id %>
                <td class="col-md-2"><%= m.competitor1.name %></td>
                <td class="col-md-1"> vs </td>
                <td class="col-md-2"><%= m.competitor2.name %></td>
                <td class="col-md-1"><%= render_score m, 1 %></td>
                <td class="col-md-1">-</td>
                <td class="col-md-1"><%= render_score m, 2 %></td>
                <td class="col-md-2"><%= m.start_time %></td>
                <td class="col-md-2"><%= m.formatted_date %></td>
              </tr>
              <% week = week + 1 unless week == m.round %>
            <% end %>
          <% end %>
          </tbody></table>
        </div>
      </div>
  </div>
  </div>
  <% end %>
</div>  
</div>

<div class="col-md-5">
  <% $redirect = @competition %>
  <% @channel = @competition.channel %>
  <%= render @competition.channel %>
</div>
            
<div class="col-md-12">
    <% if @competition.competition_type == 3  %>
          <main id="tournament">
            <% ra = 2**(Math.log2(@competition.competitors.length).ceil) %>
            <% for i in 0..@rounds.length-1 do %>
              <% ra = ra/2 %>
              <ul class="round round-<%=i + 1%>">
                <% j = 1 %>
                <li class="spacer">&nbsp;</li>
                <% @rounds[i].each do |m| %>
                  <% name1  = m.competitor1.name unless m.competitor1.nil? %>
                  <% name2  = m.competitor2.name unless m.competitor2.nil? %>
                  <% score1 = m.competitor1_score unless m.competitor1.nil? %>
                  <% score2 = m.competitor2_score unless m.competitor2.nil? %>
                  <% if m.competitor1 && m.competitor2 %>
              		  <li class="game game-top winner"><%= link_to name1, m %> <span><%= link_to score1, m %></span></li>
              		  <li class="game game-spacer">&nbsp;</li>
              		  <li class="game game-bottom "><%= link_to name2, m %><span><%= link_to score2, m %></span></li>
                  <% else %>
                    <li class="game game-top winner"><%= name1 %> <span><%= score1 %></span></li>
              		  <li class="game game-spacer">&nbsp;</li>
              		  <li class="game game-bottom "><%= name2 %><span><%= score2 %></span></li>
                  <% end %>
                  <li class="spacer">&nbsp;</li>
                  <% j+=1 %>
      	       <% end %>
      	       <% j.upto(ra) do %>
              		<li class="game game-top winner" style="visibility:hidden">fill<span>0</span></li>
              		<li class="game game-spacer" style="visibility:hidden">&nbsp;</li>
              		<li class="game game-bottom " style="visibility:hidden">fill<span>0</span></span></li>
                  <li class="spacer" style="visibility:hidden">&nbsp;</li>
      	       <% end %>
        	    </ul>
            <% end %>
            <% if @competition.winner %>
              <ul class="round round-<%=@rounds.length + 1%>">
                <b>&nbsp;&nbsp;&nbsp;<%= @competition.winner.name %></b>
              </ul>
            <% end %>
          </main>
    <% end %>
</div>